# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (daily is recommended to save Action minutes)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: Soumedhik
          template: classic
          base: header, activity, community, repositories, metadata
          base_hireable: yes
          base_indepth: yes
          config_display: large
          config_octicon: yes
          config_timezone: Asia/Kolkata
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all
          plugin_calendar: yes
          plugin_calendar_limit: 5
          plugin_code: yes
          plugin_code_days: 3
          plugin_code_lines: 12
          plugin_code_load: 400
          plugin_code_visibility: public
          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_sections: repositories
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          plugin_habits_trim: yes
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_indepth: yes
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          
          # The PageSpeed plugin is disabled for now as it's missing an API key secret.
          # To enable it, create a secret named PAGESPEED_TOKEN with your Google API Key.
          # plugin_pagespeed: yes
          # plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          # plugin_pagespeed_detailed: yes
          # plugin_pagespeed_screenshot: yes
          # plugin_pagespeed_url: soumedhik.tech
          
          plugin_people: yes
          plugin_people_identicons: yes
          plugin_people_limit: 24
          plugin_people_shuffle: yes
          plugin_people_size: 28
          plugin_people_types: followers, following
          plugin_repositories: yes
          plugin_repositories_featured: Soumedhik/Combined-Attention-and-Deep-Auto-Encoder-with-GloVe-Embedding-Features, Soumedhik/Aurora-Sight-to-Sound, Soumedhik/Resume-Insight-Engine, Soumdhik/Adaptive-Guided-Query-Retrieval-AGQ-IR-, Soumedhik/AI-Text-Detection, Soumedhik/Essay-Grading-System, Soumedhik/Image_Enhancement_Autoencoder
          plugin_repositories_order: featured, pinned, starred, random
          plugin_screenshot: yes
          plugin_screenshot_background: yes
          plugin_screenshot_mode: image
          plugin_screenshot_selector: body
          plugin_screenshot_title: Screenshot
          plugin_screenshot_url: soumedhik.tech
          plugin_screenshot_wait: 5
          
          # ------------------------------------------------------------------
          # ▼▼▼ CRITICAL FIX 1: Correct YAML syntax for viewport object ▼▼▼
          # ------------------------------------------------------------------
          plugin_screenshot_viewport: |
            {
              "width": 1280,
              "height": 1280
            }

          plugin_skyline: yes
          plugin_skyline_frames: 60
          plugin_skyline_quality: 0.5
          plugin_skyline_year: 2025
          
          # ------------------------------------------------------------------
          # ▼▼▼ CRITICAL FIX 2: Correct YAML syntax for settings object ▼▼▼
          # ------------------------------------------------------------------
          plugin_skyline_settings: |
            {
              "url": "https://skyline.github.com/${login}/${year}",
              "ready": "[...document.querySelectorAll('span')].map(span => span.innerText).includes('Share on Twitter')",
              "wait": 1,
              "hide": "button, footer, a"
            }

          plugin_stargazers: yes
          plugin_stargazers_charts: yes
          plugin_stargazers_charts_type: classic
          plugin_stargazers_days: 14
          # The worldmap is disabled as it's missing an API key. Re-enable if you add the token.
          plugin_stargazers_worldmap: no 
          plugin_stars: yes
          plugin_stars_limit: 4
          
          # All other plugins from your original config are here...
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: starred
          plugin_topics_sort: stars
          plugin_traffic: yes
          repositories_forks: yes
