# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on: 
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Also run on pushes to main/master branch
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: Soumedhik
          template: classic
          base: header, activity, community, repositories, metadata
          base_hireable: yes
          base_indepth: yes
          config_display: large
          config_octicon: yes
          config_timezone: Asia/Kolkata
          
          # PLUGINS CONFIGURATION
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all
          
          plugin_code: yes
          plugin_code_days: 3
          plugin_code_lines: 12
          plugin_code_load: 400
          plugin_code_visibility: public
          
          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_sections: repositories
          
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          plugin_habits_trim: yes
          
          plugin_introduction: yes
          plugin_introduction_title: yes
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          plugin_languages: yes
          plugin_languages_indepth: no
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          
          plugin_people: yes
          plugin_people_identicons: yes
          plugin_people_limit: 24
          plugin_people_shuffle: yes
          plugin_people_size: 28
          plugin_people_types: followers, following
          
          plugin_repositories: yes
          plugin_repositories_featured: Soumedhik/Combined-Attention-and-Deep-Auto-Encoder-with-GloVe-Embedding-Features, Soumedhik/Aurora-Sight-to-Sound, Soumedhik/Resume-Insight-Engine, Soumedhik/Adaptive-Guided-Query-Retrieval-AGQ-IR-, Soumedhik/AI-Text-Detection, Soumedhik/Essay-Grading-System, Soumedhik/Image_Enhancement_Autoencoder
          plugin_repositories_order: featured, pinned, starred, random
          
          plugin_stargazers: yes
          plugin_stargazers_charts: yes
          plugin_stargazers_charts_type: classic
          plugin_stargazers_days: 14
          plugin_stargazers_worldmap: no
          
          plugin_stars: yes
          plugin_stars_limit: 4
          
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: starred
          plugin_topics_sort: stars
          
          plugin_traffic: yes
          repositories_forks: yes
